object Versions {
    const val jvm = "1.8"
    const val kotlin = "1.3.72"
    const val graal = "20.1.0"

    // Gradle plugins
    const val shadow = "5.2.0"
    const val sqlDelight = "1.4.0"
    const val proguard = "7.0.0"

    // Libraries
    const val argon2 = "2.7"
    const val autoprefixer = "9.8.4"
    const val babel = "7.2.0"
    const val babelLoader = "8.1.0"
    const val babelPluginClassProperties = "7.10.1"
    const val babelPresetEnv = "7.2.0"
    const val browserMob = "2.1.5"
    const val cssLoader = "3.6.0"
    const val cssnano = "4.1.10"
    const val fileLoader = "6.0.0"
    const val jsCookie = "2.2.1"
    const val jwarc = "0.13.0"
    const val koin = "2.1.5"
    const val kotlinCoroutines = "1.3.7"
    const val kotlinReact = "16.13.1-pre.105-kotlin-1.3.72"
    const val kotlinReactRouter = "5.1.2-pre.107-kotlin-1.3.72"
    const val kotlinSerialization = "0.20.0"
    const val ktor = "1.3.2"
    const val logback = "1.2.3"
    const val markText = "https://github.com/drampelt/marktext#markstash"
    const val postcssLoader = "3.0.0"
    const val postcssImport = "12.0.1"
    const val postcssNested = "4.2.3"
    const val react = "16.13.1"
    const val reactRouter = "5.1.2"
    const val readability4j = "1.0.3"
    const val selenium = "3.8.1"
    const val snapsvg = "0.5.1"
    const val sqlite = "3.21.0.1"
    const val styleLoader = "1.2.1"
    const val svgSpriteLoader = "5.0.0"
    const val tailwindcss = "1.4.6"
    const val tailwindUi = "0.3.1"
    const val urlLoader = "4.1.0"
    const val webextensionPolyfill = "0.6.0"
}

object Dependencies {
    const val argon2 = "de.mkammerer:argon2-jvm-nolibs:${Versions.argon2}"
    const val browserMob = "net.lightbody.bmp:browsermob-core:2.1.5"
    const val jwarc = "org.netpreserve:jwarc:${Versions.jwarc}"
    const val koinKtor = "org.koin:koin-ktor:${Versions.koin}"
    const val kotlinCoroutinesCommon = "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:${Versions.kotlinCoroutines}"
    const val kotlinCoroutinesJs = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:${Versions.kotlinCoroutines}"
    const val kotlinReact = "org.jetbrains:kotlin-react:${Versions.kotlinReact}"
    const val kotlinReactDom = "org.jetbrains:kotlin-react-dom:${Versions.kotlinReact}"
    const val kotlinReactRouterDom = "org.jetbrains:kotlin-react-router-dom:${Versions.kotlinReactRouter}"
    const val kotlinSerializationCommon = "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:${Versions.kotlinSerialization}"
    const val kotlinSerializationJs = "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:${Versions.kotlinSerialization}"
    const val kotlinSerializationJvm = "org.jetbrains.kotlinx:kotlinx-serialization-runtime:${Versions.kotlinSerialization}"
    const val ktorAuthJwt = "io.ktor:ktor-auth-jwt:${Versions.ktor}"
    const val ktorClientCore = "io.ktor:ktor-client-core:${Versions.ktor}"
    const val ktorClientJs = "io.ktor:ktor-client-js:${Versions.ktor}"
    const val ktorClientSerialization = "io.ktor:ktor-client-serialization:${Versions.ktor}"
    const val ktorClientSerializationJs = "io.ktor:ktor-client-serialization-js:${Versions.ktor}"
    const val ktorLocations = "io.ktor:ktor-locations:${Versions.ktor}"
    const val ktorSerialization = "io.ktor:ktor-serialization:${Versions.ktor}"
    const val ktorServerCio = "io.ktor:ktor-server-cio:${Versions.ktor}"
    const val logbackClassic = "ch.qos.logback:logback-classic:${Versions.logback}"
    const val proguard = "com.guardsquare:proguard-gradle:${Versions.proguard}"
    const val readability4j = "net.dankito.readability4j:readability4j:${Versions.readability4j}"
    const val selenium = "org.seleniumhq.selenium:selenium-java:${Versions.selenium}"
    const val sqlDelightGradle = "com.squareup.sqldelight:gradle-plugin:${Versions.sqlDelight}"
    const val sqlDelightSqlite = "com.squareup.sqldelight:sqlite-driver:${Versions.sqlDelight}"
    const val sqlite = "org.xerial:sqlite-jdbc:${Versions.sqlite}"
    const val svm = "org.graalvm.nativeimage:svm:${Versions.graal}"
}
